/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "uber.h"

bool_t
xdr_InfoAuto (XDR *xdrs, InfoAuto *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->disponible))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->x))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->y))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->tipoUber, 20))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->tarifa))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->placas, 10))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Solicitud (XDR *xdrs, Solicitud *objp)
{
	register int32_t *buf;

	 if (!xdr_float (xdrs, &objp->x_pasajero))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->y_pasajero))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_TerminarViajeArgs (XDR *xdrs, TerminarViajeArgs *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->placas, 10))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->costo))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->posicion_final, 20))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Estado (XDR *xdrs, Estado *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->viajes_realizados))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->autos_disponibles))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->ganancia_total))
		 return FALSE;
	return TRUE;
}
